api/urls.py
from django.urls import path

from api.services import DeputyService
from api.services import VoteService
from api.services import LegislatureService
from api.services import PartyService
from api.services import PropositionService

app_name = 'api'
urlpatterns = [
    # path('error/<string:message>', views.error, name='error'),
    path('deputies/', DeputyService.deputies, name='deputies'),
    path('deputies/<int:deputy_id>', DeputyService.deputy, name='deputy'),
    path('votes/', VoteService.votes, name='votes'),
    path('legislatures/', LegislatureService.legislatures, name='legislatures'),
    path('parties/', PartyService.parties, name='parties'),
    path('parties/<int:party_id>', PartyService.party, name='party'),
    path('propositions/', PropositionService.propositions, name='propositions'),
    path('propositions/<int:proposition_id>',
         PropositionService.proposition, name='proposition')
]

parliament/urls.py
from django.urls import path
from parliament.views import Home
from parliament.views import Deputy
from parliament.views import Proposition

app_name = 'home'
urlpatterns = [
    path('', Home.index, name='index_page'),
    path('deputies/', Deputy.deputies_list, name='deputies_list_page'),
    path('deputies/search', Deputy.deputies_search, name='deputies_search_page'),
    path('deputies/<int:pk>/', Deputy.deputy_detail,
         name='deputy_detail_page'),
    path('propositions/', Proposition.propositions_list,
         name='propositions_list_page'),
    path('propositions/federal', Proposition.federal,
         name='propositions_federal'),
    path('propositions/<int:pk>/', Proposition.proposition_detail,
         name='proposition_detail_page'),
]

zinneke_babeleir_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
import os

urlpatterns = i18n_patterns(
    path('', include('parliament.urls', namespace='home')),
    path('api/', include('api.urls', namespace='api')),
    path(os.environ.get('ADMIN_URL', 'admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
)

parliament/views/deputy_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition


def deputies_list(request):
    deputies_bru = Deputy.get_all_by_last_legislature_parliament('BRU')
    deputies_fed = Deputy.get_all_by_last_legislature_parliament('FED')
    deputies_vla = Deputy.get_all_by_last_legislature_parliament('VLA')
    deputies_wal = Deputy.get_all_by_last_legislature_parliament('WAL')
    deputies_fra = Deputy.get_all_by_last_legislature_parliament('FRA')
    deputies_ger = Deputy.get_all_by_last_legislature_parliament('GER')
    deputies_sen = Deputy.get_all_by_last_legislature_parliament('SEN')
    context = {
        'deputies_fed': deputies_fed,
        'deputies_bru': deputies_bru,
        'deputies_vla': deputies_vla,
        'deputies_wal': deputies_wal,
        'deputies_fra': deputies_fra,
        'deputies_ger': deputies_ger,
        'deputies_sen': deputies_sen
    }
    return render(request, 'parliament/pages/deputies.html', context)


def deputies_search(request):
    query = request.GET.get('query')
    deputies = []
    if query is not None:
        deputies = Deputy.get_all_filter_name(query)

    context = {
        'deputies': deputies,
        'query': query
    }
    return render(request, 'parliament/pages/deputies_search.html', context)


def deputy_detail(request, pk):
    deputy = Deputy.get_one(pk)
    propositions = Proposition.get_all_for_deputy(pk)

    context = {
        'deputy': deputy,
        'propositions': propositions
    }
    return render(request, 'parliament/pages/deputy.html', context)

parliament/views/home_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition


def index(request):
    propositions_fed = Proposition.get_all_last_by_parliament('FED')
    # propositions_bru = Proposition.get_all_last_by_parliament('BRU')
    # propositions_vla = Proposition.get_all_last_by_parliament('VLA')
    # propositions_wal = Proposition.get_all_last_by_parliament('WAL')
    # propositions_fra = Proposition.get_all_last_by_parliament('FRA')
    # propositions_ger = Proposition.get_all_last_by_parliament('GER')
    # propositions_sen = Proposition.get_all_last_by_parliament('SEN')
    context = {
        'propositions_fed': propositions_fed
    }
    return render(request, 'parliament/pages/index.html', context)

parliament/views/proposition_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition
from repository.repos import Legislature


def propositions_list(request):
    propositions = Proposition.get_all()
    context = {
        'propositions': propositions,
    }
    return render(request, 'parliament/pages/propositions.html', context)


def proposition_detail(request, pk):
    proposition = Proposition.get_one(pk)
    deputies_for = Deputy.get_all_voted_type_proposition(pk, 'for')
    deputies_against = Deputy.get_all_voted_type_proposition(pk, 'against')
    deputies_abstention = Deputy.get_all_voted_type_proposition(
        pk, 'abstention')
    deputies_absent = Deputy.get_all_voted_type_proposition(pk, 'absent')

    context = {
        'proposition': proposition,
        'deputies_for': deputies_for,
        'deputies_against': deputies_against,
        'deputies_abstention': deputies_abstention,
        'deputies_absent': deputies_absent
    }
    return render(request, 'parliament/pages/proposition.html', context)


def federal(request):
    propositions = Proposition.get_all_by_last_legislature_parliament('FED')
    deputies = Deputy.get_all_by_last_legislature_parliament('FED')
    legislature = Legislature.get_one_last_by_parliament('FED')
    context = {
        'propositions': propositions,
        'deputies': deputies,
        'legislature': legislature
    }
    return render(request, 'parliament/pages/federal.html', context)

parliament/templates/parliament/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <title>Zinneke babeleir!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/icon type">

  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/fa-all.min.css' %}" />

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light ">
    <a class="navbar-brand" href="{% url 'home:index_page' %}">Zinneke babeleir</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item">
          <a href="{% url 'home:propositions_list_page' %}" class="nav-link">{% trans "VotesPropositions" %}</a>
        </li> -->
        <li class="nav-item">
          <a href="{% url 'home:deputies_list_page' %}" class="nav-link">
            {% trans "TheActualDeputies" %}
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {% trans "Parliaments" %}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'home:propositions_federal' %}">{% trans "Federal" %}</a>
          </div>
        </li>
      </ul>

      <form class="form-inline" action="{% url 'home:deputies_search_page' %}" method="get">
        <div class="form-group">
          <input id="searchForm" name="query" class="form-control" placeholder="{% trans 'DeputiesSearch' %}"
            class="form-control" type="search">
          <button class="btn" type="submit"><i class="fas fa-search color-secondary"></i></button>
        </div>
      </form>

    </div>
  </nav>

  <div class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>

  <footer>
    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language" id="dropdown-change-language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}

        {% get_language_info_list for LANGUAGES as languages %}

        {% for language in languages %}
        {% if language.code == LANGUAGE_CODE %} selected
        <option value="{{ language.code }}" selected>
          {{ language.name_local }} ({{ language.code }})
        </option>
        {%else%}
        <option value="{{ language.code }}">
          {{ language.name_local }} ({{ language.code }})
        </option>
        {% endif %}
        {% endfor %}
      </select>
      <input type="submit" value="Go" id="button-change-language">
    </form>

    <a href="https://github.com/FreeCaribou/ZinnekeBabeleir"><i class="fab fa-github color-secondary"></i></a>
  </footer>

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>