api/urls.py
from django.urls import path

from api.services import DeputyService
from api.services import VoteService
from api.services import LegislatureService
from api.services import PartyService
from api.services import PropositionService

app_name = 'api'
urlpatterns = [
    # path('error/<string:message>', views.error, name='error'),
    path('deputies/', DeputyService.deputies, name='deputies'),
    path('deputies/<int:deputy_id>', DeputyService.deputy, name='deputy'),
    path('votes/', VoteService.votes, name='votes'),
    path('legislatures/', LegislatureService.legislatures, name='legislatures'),
    path('parties/', PartyService.parties, name='parties'),
    path('parties/<int:party_id>', PartyService.party, name='party'),
    path('propositions/', PropositionService.propositions, name='propositions'),
    path('propositions/<int:proposition_id>',
         PropositionService.proposition, name='proposition')
]

parliament/urls.py
from django.urls import path
from parliament.views import Home
from parliament.views import Deputy
from parliament.views import Proposition

app_name = 'home'
urlpatterns = [
    path('', Home.index, name='index_page'),
    path('deputies/', Deputy.deputies_list, name='deputies_list_page'),
    path('deputies/search', Deputy.deputies_search, name='deputies_search_page'),
    path('deputies/<int:pk>/', Deputy.deputy_detail,
         name='deputy_detail_page'),
    path('propositions/', Proposition.propositions_list,
         name='propositions_list_page'),
    path('propositions/federal', Proposition.federal,
         name='propositions_federal'),
    path('propositions/<int:pk>/', Proposition.proposition_detail,
         name='proposition_detail_page'),
]

zinneke_babeleir_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
import os

urlpatterns = i18n_patterns(
    path('', include('parliament.urls', namespace='home')),
    path('api/', include('api.urls', namespace='api')),
    path(os.environ.get('ADMIN_URL', 'admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
)

parliament/views/deputy_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition


def deputies_list(request):
    deputies_bru = Deputy.get_all_by_last_legislature_parliament('BRU')
    deputies_fed = Deputy.get_all_by_last_legislature_parliament('FED')
    deputies_vla = Deputy.get_all_by_last_legislature_parliament('VLA')
    deputies_wal = Deputy.get_all_by_last_legislature_parliament('WAL')
    deputies_fra = Deputy.get_all_by_last_legislature_parliament('FRA')
    deputies_ger = Deputy.get_all_by_last_legislature_parliament('GER')
    deputies_sen = Deputy.get_all_by_last_legislature_parliament('SEN')
    context = {
        'deputies_fed': deputies_fed,
        'deputies_bru': deputies_bru,
        'deputies_vla': deputies_vla,
        'deputies_wal': deputies_wal,
        'deputies_fra': deputies_fra,
        'deputies_ger': deputies_ger,
        'deputies_sen': deputies_sen
    }
    return render(request, 'parliament/pages/deputies.html', context)


def deputies_search(request):
    query = request.GET.get('query')
    deputies = []
    if query is not None:
        deputies = Deputy.get_all_filter_name(query)

    context = {
        'deputies': deputies,
        'query': query
    }
    return render(request, 'parliament/pages/deputies_search.html', context)


def deputy_detail(request, pk):
    deputy = Deputy.get_one(pk)
    propositions = Proposition.get_all_for_deputy(pk)

    context = {
        'deputy': deputy,
        'propositions': propositions
    }
    return render(request, 'parliament/pages/deputy.html', context)

parliament/views/home_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition


def index(request):
    propositions_fed = Proposition.get_all_last_by_parliament('FED')
    # propositions_bru = Proposition.get_all_last_by_parliament('BRU')
    # propositions_vla = Proposition.get_all_last_by_parliament('VLA')
    # propositions_wal = Proposition.get_all_last_by_parliament('WAL')
    # propositions_fra = Proposition.get_all_last_by_parliament('FRA')
    # propositions_ger = Proposition.get_all_last_by_parliament('GER')
    # propositions_sen = Proposition.get_all_last_by_parliament('SEN')
    context = {
        'propositions_fed': propositions_fed
    }
    return render(request, 'parliament/pages/index.html', context)

parliament/views/proposition_views.py
from django.shortcuts import render
from django.http import HttpResponse
from repository.repos import Deputy
from repository.repos import Proposition
from repository.repos import Legislature


def propositions_list(request):
    propositions = Proposition.get_all()
    context = {
        'propositions': propositions,
    }
    return render(request, 'parliament/pages/propositions.html', context)


def proposition_detail(request, pk):
    proposition = Proposition.get_one(pk)
    deputies_for = Deputy.get_all_voted_type_proposition(pk, 'for')
    deputies_against = Deputy.get_all_voted_type_proposition(pk, 'against')
    deputies_abstention = Deputy.get_all_voted_type_proposition(
        pk, 'abstention')
    deputies_absent = Deputy.get_all_voted_type_proposition(pk, 'absent')

    context = {
        'proposition': proposition,
        'deputies_for': deputies_for,
        'deputies_against': deputies_against,
        'deputies_abstention': deputies_abstention,
        'deputies_absent': deputies_absent
    }
    return render(request, 'parliament/pages/proposition.html', context)


def federal(request):
    propositions = Proposition.get_all_by_last_legislature_parliament('FED')
    deputies = Deputy.get_all_by_last_legislature_parliament('FED')
    legislature = Legislature.get_one_last_by_parliament('FED')
    context = {
        'propositions': propositions,
        'deputies': deputies,
        'legislature': legislature
    }
    return render(request, 'parliament/pages/federal.html', context)

parliament/templates/parliament/components/deputies_list.html
{% load i18n %}
{% if deputies|length_is:"0" %}
<p>{% trans "NoDeputyFound" %}</p>
{% else %}
<ul class="list-group list-group-flush">
  {% for d in deputies %}
  <li class="list-group-item">
    <a href="{% url 'home:deputy_detail_page' pk=d.pk %}">
      {{d.first_name}} {{d.last_name}} / {{d.party.name}}
    </a>
  </li>
  {% endfor %}
</ul>
{% endif %}

parliament/templates/parliament/components/propositions_list.html
{% load i18n %}

{% if propositions|length_is:"0" %}
<p>{% trans "NoPropositionFound" %}</p>
{% else %}
<ul class="list-group">
  {% for p in propositions %}
  <li class="list-group-item flex-space-between">
    <a href="{% url 'home:proposition_detail_page' pk=p.pk %}">
      {{p.date | date:"Y F j"}} | {{p.legislature.parliament}}
      <div>{{p.title_fr}}</div>
      <div>{{p.title_nl}}</div>
    </a>
    {% if p.vote_type_code %}
    <span>
      {% if p.vote_type_code == 'for' %}

      <i class="fas fa-check-circle color-for" title="{% trans 'For' %}" alt="{% trans 'For' %}"></i>
      {% elif p.vote_type_code == 'against' %}
      <i class="fas fa-times-circle color-against" title="{% trans 'Against' %}" alt="{% trans 'Against' %}"></i>
      {% elif p.vote_type_code == 'abstention' %}
      <i class="fas fa-minus-circle color-abstention" title="{% trans 'Abstention' %}"
        alt="{% trans 'Abstention' %}"></i>
      {% elif p.vote_type_code == 'absent' %}
      <i class="fas fa-circle color-absent" title="{% trans 'Absent' %}" alt="{% trans 'Absent' %}"></i>
      {% else %}
      <i class="fas fa-question-circle color-primary" title="unknow" alt="unknow"></i>
      {% endif %}
    </span>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endif %}

parliament/templates/parliament/components/votes_list.html
{% if votes|length_is:"0" %}
<p>No vote</p>
{% else %}
<h1>Votes:</h1>
<ul class="list-group">
  {% for v in votes %}
  <li class="list-group-item">
    {{v.type_code}} {{v.proposition.title_fr}} / {{v.proposition.title_nl}} - {{v.deputy.first_name}}
    {{v.deputy.last_name}}
  </li>
  {% endfor %}
</ul>
{% endif %}